name: 'Flutter Test'
on:
  pull_request:
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2               # checkout the repo
      - uses: subosito/flutter-action@v2        # checkout the repo
        with:
          flutter-version: "3.0.2"
      - run: flutter pub get
      - run: flutter test
