name: 'Flutter Test'
on:
  pull_request:
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2               # checkout the repo
      - uses: subosito/flutter-action@v2        # checkout the repo
        with:
          flutter-version: "3.0.2"
      - name: Run tests for admin
        working-directory: ./admin
        run: |
          flutter pub get
          flutter test test/widget_test.dart
      - name: Run tests for wallet
        working-directory: ./wallet
        run: |
          open -a Simulator.app
          flutter pub get
          flutter test test/widget_test.dart
          flutter test integration_test

