name: CI/CD Pipeline
on:
  pull_request:


jobs:
  test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TestProject Execute Jobs
        uses: Mahan-F/test-project-action@v1
        with:
          project_id: LyJAr9hQCkutnpP3AWR59Q
          api_key: oIlyzhlLPENDJrDmp_fPazWjEYtLs1h8MVvDfuS8ii81